BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `WEIGHTAGE` (
	`MIDSEM`	INTEGER NOT NULL,
	`COMPRE`	INTEGER NOT NULL,
	`QUIZ`	INTEGER NOT NULL,
	`ASSIGNMENT`	INTEGER NOT NULL,
	`TOTALMARKS`	INTEGER NOT NULL,
	PRIMARY KEY(`MIDSEM`,`COMPRE`,`QUIZ`,`ASSIGNMENT`,`TOTALMARKS`)
);
CREATE TABLE IF NOT EXISTS `TEACHER` (
	`TID`	TEXT NOT NULL,
	`TNAME`	TEXT NOT NULL,
	`DESIGNATION`	TEXT,
	`DEPARTMENT`	TEXT,
	`PASSWORD`	TEXT NOT NULL,
	PRIMARY KEY(`TID`)
);
CREATE TABLE IF NOT EXISTS `STUDENTCOURSE` (
	`SID`	TEXT NOT NULL,
	`CID`	TEXT NOT NULL,
	FOREIGN KEY(`CID`) REFERENCES `COURSE`(`CID`),
	FOREIGN KEY(`SID`) REFERENCES `STUDENT`(`SID`),
	PRIMARY KEY(`SID`,`CID`)
);
CREATE TABLE IF NOT EXISTS `STUDENT` (
	`SID`	TEXT NOT NULL,
	`SNAME`	TEXT,
	`PASSWORD`	TEXT,
	PRIMARY KEY(`SID`)
);
CREATE TABLE IF NOT EXISTS `COURSEWEIGHTAGE` (
	`CID`	INTEGER NOT NULL,
	`CNAME`	INTEGER,
	`CREDITS`	INTEGER,
	`MIDSEM`	INTEGER,
	`COMPRE`	INTEGER,
	`QUIZ`	INTEGER,
	`ASSIGNMENT`	INTEGER,
	`TOTALMARKS`	INTEGER,
	PRIMARY KEY(`CID`)
	FOREIGN KEY(`TOTALMARKS`,`MIDSEM`,`COMPRE`,`QUIZ`,`ASSIGNMENT`) REFERENCES `WEIGHTAGE`(`TOTALMARKS`,`MIDSEM`,`COMPRE`,`QUIZ`,`ASSIGNMENT`)

);
CREATE TABLE IF NOT EXISTS `COURSENAME2` (
	`CID`	TEXT NOT NULL,
	`CREDITS`	INTEGER,
	PRIMARY KEY(`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSEMARKS3` (
	`CID`	INTEGER NOT NULL,
	`SID`	INTEGER NOT NULL,
	`MIDSEM`	INTEGER,
	`COMPRE`	INTEGER,
	PRIMARY KEY(`SID`,`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSEMARKS1` (
	`CID`	TEXT NOT NULL,
	`CNAME`	TEXT,
	PRIMARY KEY(`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSEFEEDBACK` (
	`CID`	TEXT NOT NULL,
	`FEEDBACK`	TEXT NOT NULL,
	PRIMARY KEY(`CID`,`FEEDBACK`)
);
CREATE TABLE IF NOT EXISTS `COURSEDISCUSSION4` (
	`CID`	TEXT NOT NULL,
	`SID`	TEXT NOT NULL,
	`TIME`	TEXT NOT NULL,
	PRIMARY KEY(`TIME`,`SID`,`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSEDISCUSSION3` (
	`SID`	TEXT NOT NULL,
	`TIME`	TEXT NOT NULL,
	`COMMENT`	TEXT,
	PRIMARY KEY(`SID`,`TIME`)
);
CREATE TABLE IF NOT EXISTS `COURSEDISCUSSION2` (
	`CID`	TEXT NOT NULL,
	`CREDITS`	INTEGER,
	PRIMARY KEY(`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSEDISCUSSION1` (
	`CID`	TEXT NOT NULL,
	`CNAME`	TEXT,
	PRIMARY KEY(`CID`)
);
CREATE TABLE IF NOT EXISTS `COURSE` (
	`CID`	TEXT NOT NULL,
	`CNAME`	TEXT,
	`CREDITS`	INTEGER,
	`TID`	TEXT,
	FOREIGN KEY(`TID`) REFERENCES `TEACHER`(`TID`),
	PRIMARY KEY(`CID`)
);
CREATE TABLE IF NOT EXISTS `APPOINTMENT` (
	`SID`	TEXT NOT NULL,
	`TIME`	TEXT NOT NULL,
	`TID`	TEXT,
	FOREIGN KEY(`TID`) REFERENCES `TEACHER`(`TID`),
	PRIMARY KEY(`SID`,`TIME`)
);
COMMIT;
